<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>eb4522a3-3939-4ce2-b30e-106e712f057f</testSuiteGuid>
   <testCaseLink>
      <guid>706a0067-9293-4238-b120-97479637170f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC-Onboarding/Onboarding</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3c5b0de4-454b-46f4-b216-2dbba8076aa8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC-Login/Verify Element</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>79d5b025-6543-42bf-ac18-08f19b760a26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC-Login/Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a66f223-f6f1-48e9-8135-c7ead591e145</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7747d91b-669b-4653-ad5e-40ecf97ab3da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0a9a787-97c2-4937-a83c-54df7d7833b3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
